import { PrismaClient } from "@prisma/client"

export async function seedCurrencies(prisma: PrismaClient) {
    const currencies = [
        { code: "USD", name: "US Dollar", rate: 1 },
        { code: "AED", name: "UAE Dirham", rate: 3.67 },
        { code: "AFN", name: "Afghan Afghani", rate: 70.79 },
        { code: "ALL", name: "Albanian Lek", rate: 93.7 },
        { code: "AMD", name: "Armenian Dram", rate: 388.06 },
        { code: "ANG", name: "Netherlands Antillean Guilder", rate: 1.79 },
        { code: "AOA", name: "Angolan Kwanza", rate: 865.03 },
        { code: "ARS", name: "Argentine Peso", rate: 911.67 },
        { code: "AUD", name: "Australian Dollar", rate: 1.5 },
        { code: "AWG", name: "Aruban Florin", rate: 1.79 },
        { code: "AZN", name: "Azerbaijani Manat", rate: 1.7 },
        { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", rate: 1.83 },
        { code: "BBD", name: "Barbadian Dollar", rate: 2 },
        { code: "BDT", name: "Bangladeshi Taka", rate: 117.49 },
        { code: "BGN", name: "Bulgarian Lev", rate: 1.83 },
        { code: "BHD", name: "Bahraini Dinar", rate: 0.376 },
        { code: "BIF", name: "Burundian Franc", rate: 2865.62 },
        { code: "BMD", name: "Bermudian Dollar", rate: 1 },
        { code: "BND", name: "Brunei Dollar", rate: 1.36 },
        { code: "BOB", name: "Bolivian Boliviano", rate: 6.92 },
        { code: "BRL", name: "Brazilian Real", rate: 5.52 },
        { code: "BSD", name: "Bahamian Dollar", rate: 1 },
        { code: "BTN", name: "Bhutanese Ngultrum", rate: 83.47 },
        { code: "BWP", name: "Botswana Pula", rate: 13.63 },
        { code: "BYN", name: "Belarusian Ruble", rate: 3.28 },
        { code: "BZD", name: "Belize Dollar", rate: 2 },
        { code: "CAD", name: "Canadian Dollar", rate: 1.37 },
        { code: "CDF", name: "Congolese Franc", rate: 2826.99 },
        { code: "CHF", name: "Swiss Franc", rate: 0.898 },
        { code: "CLP", name: "Chilean Peso", rate: 950.99 },
        { code: "CNY", name: "Chinese Yuan Renminbi", rate: 7.28 },
        { code: "COP", name: "Colombian Peso", rate: 4129.85 },
        { code: "CRC", name: "Costa Rican Colon", rate: 522.5 },
        { code: "CUP", name: "Cuban Peso", rate: 24 },
        { code: "CVE", name: "Cape Verdean Escudo", rate: 103.02 },
        { code: "CZK", name: "Czech Koruna", rate: 23.37 },
        { code: "DJF", name: "Djiboutian Franc", rate: 177.72 },
        { code: "DKK", name: "Danish Krone", rate: 6.97 },
        { code: "DOP", name: "Dominican Peso", rate: 59.02 },
        { code: "DZD", name: "Algerian Dinar", rate: 134.69 },
        { code: "EGP", name: "Egyptian Pound", rate: 48.03 },
        { code: "ERN", name: "Eritrean Nakfa", rate: 15 },
        { code: "ETB", name: "Ethiopian Birr", rate: 57.74 },
        { code: "EUR", name: "Euro", rate: 0.934 },
        { code: "FJD", name: "Fijian Dollar", rate: 2.23 },
        { code: "FKP", name: "Falkland Islands Pound", rate: 0.791 },
        { code: "FOK", name: "Faroese Krona", rate: 6.97 },
        { code: "GBP", name: "British Pound", rate: 0.791 },
        { code: "GEL", name: "Georgian Lari", rate: 2.83 },
        { code: "GGP", name: "Guernsey Pound", rate: 0.791 },
        { code: "GHS", name: "Ghanaian Cedi", rate: 15.28 },
        { code: "GIP", name: "Gibraltar Pound", rate: 0.791 },
        { code: "GMD", name: "Gambian Dalasi", rate: 66.24 },
        { code: "GNF", name: "Guinean Franc", rate: 8576.05 },
        { code: "GTQ", name: "Guatemalan Quetzal", rate: 7.76 },
        { code: "GYD", name: "Guyanese Dollar", rate: 209.01 },
        { code: "HKD", name: "Hong Kong Dollar", rate: 7.81 },
        { code: "HNL", name: "Honduran Lempira", rate: 24.73 },
        { code: "HRK", name: "Croatian Kuna", rate: 7.04 },
        { code: "HTG", name: "Haitian Gourde", rate: 132.37 },
        { code: "HUF", name: "Hungarian Forint", rate: 370.43 },
        { code: "IDR", name: "Indonesian Rupiah", rate: 16412.74 },
        { code: "ILS", name: "Israeli New Shekel", rate: 3.76 },
        { code: "IMP", name: "Isle of Man Pound", rate: 0.791 },
        { code: "INR", name: "Indian Rupee", rate: 83.47 },
        { code: "IQD", name: "Iraqi Dinar", rate: 1309.37 },
        { code: "IRR", name: "Iranian Rial", rate: 42051.19 },
        { code: "ISK", name: "Icelandic Krona", rate: 139.18 },
        { code: "JEP", name: "Jersey Pound", rate: 0.791 },
        { code: "JMD", name: "Jamaican Dollar", rate: 155.91 },
        { code: "JOD", name: "Jordanian Dinar", rate: 0.709 },
        { code: "JPY", name: "Japanese Yen", rate: 160.64 },
        { code: "KES", name: "Kenyan Shilling", rate: 128.85 },
        { code: "KGS", name: "Kyrgyzstani Som", rate: 86.62 },
        { code: "KHR", name: "Cambodian Riel", rate: 4095.53 },
        { code: "KID", name: "Kiribati Dollar", rate: 1.5 },
        { code: "KMF", name: "Comorian Franc", rate: 459.66 },
        { code: "KRW", name: "South Korean Won", rate: 1386.7 },
        { code: "KWD", name: "Kuwaiti Dinar", rate: 0.307 },
        { code: "KYD", name: "Cayman Islands Dollar", rate: 0.833 },
        { code: "KZT", name: "Kazakhstani Tenge", rate: 466.87 },
        { code: "LAK", name: "Laotian Kip", rate: 21994.32 },
        { code: "LBP", name: "Lebanese Pound", rate: 89500 },
        { code: "LKR", name: "Sri Lankan Rupee", rate: 305.29 },
        { code: "LRD", name: "Liberian Dollar", rate: 194.47 },
        { code: "LSL", name: "Lesotho Loti", rate: 18.44 },
        { code: "LYD", name: "Libyan Dinar", rate: 4.87 },
        { code: "MAD", name: "Moroccan Dirham", rate: 9.94 },
        { code: "MDL", name: "Moldovan Leu", rate: 17.91 },
        { code: "MGA", name: "Malagasy Ariary", rate: 4486.25 },
        { code: "MKD", name: "Macedonian Denar", rate: 57.53 },
        { code: "MMK", name: "Myanmar Kyat", rate: 2098.81 },
        { code: "MNT", name: "Mongolian Tugrik", rate: 3388.44 },
        { code: "MOP", name: "Macanese Pataca", rate: 8.04 },
        { code: "MRU", name: "Mauritanian Ouguiya", rate: 39.4 },
        { code: "MUR", name: "Mauritian Rupee", rate: 47.08 },
        { code: "MVR", name: "Maldivian Rufiyaa", rate: 15.44 },
        { code: "MWK", name: "Malawian Kwacha", rate: 1740.11 },
        { code: "MXN", name: "Mexican Peso", rate: 18.44 },
        { code: "MYR", name: "Malaysian Ringgit", rate: 4.72 },
        { code: "MZN", name: "Mozambican Metical", rate: 63.71 },
        { code: "NAD", name: "Namibian Dollar", rate: 18.44 },
        { code: "NGN", name: "Nigerian Naira", rate: 1520.16 },
        { code: "NIO", name: "Nicaraguan Cordoba", rate: 36.8 },
        { code: "NOK", name: "Norwegian Krone", rate: 10.66 },
        { code: "NPR", name: "Nepalese Rupee", rate: 133.55 },
        { code: "NZD", name: "New Zealand Dollar", rate: 1.64 },
        { code: "OMR", name: "Omani Rial", rate: 0.384 },
        { code: "PAB", name: "Panamanian Balboa", rate: 1 },
        { code: "PEN", name: "Peruvian Sol", rate: 3.82 },
        { code: "PGK", name: "Papua New Guinean Kina", rate: 3.86 },
        { code: "PHP", name: "Philippine Peso", rate: 58.69 },
        { code: "PKR", name: "Pakistani Rupee", rate: 278.65 },
        { code: "PLN", name: "Polish Zloty", rate: 4.03 },
        { code: "PYG", name: "Paraguayan Guarani", rate: 7513.62 },
        { code: "QAR", name: "Qatari Riyal", rate: 3.64 },
        { code: "RON", name: "Romanian Leu", rate: 4.65 },
        { code: "RSD", name: "Serbian Dinar", rate: 109.38 },
        { code: "RUB", name: "Russian Ruble", rate: 85.73 },
        { code: "RWF", name: "Rwandan Franc", rate: 1319.49 },
        { code: "SAR", name: "Saudi Riyal", rate: 3.75 },
        { code: "SBD", name: "Solomon Islands Dollar", rate: 8.47 },
        { code: "SCR", name: "Seychellois Rupee", rate: 13.75 },
        { code: "SDG", name: "Sudanese Pound", rate: 511.05 },
        { code: "SEK", name: "Swedish Krona", rate: 10.62 },
        { code: "SGD", name: "Singapore Dollar", rate: 1.36 },
        { code: "SHP", name: "Saint Helena Pound", rate: 0.791 },
        { code: "SLE", name: "Sierra Leonean Leone", rate: 22.56 },
        { code: "SLL", name: "Sierra Leonean Leone", rate: 22562.62 },
        { code: "SOS", name: "Somali Shilling", rate: 570.87 },
        { code: "SRD", name: "Surinamese Dollar", rate: 31.1 },
        { code: "SSP", name: "South Sudanese Pound", rate: 1968.69 },
        { code: "STN", name: "Sao Tome and Principe Dobra", rate: 22.89 },
        { code: "SYP", name: "Syrian Pound", rate: 12908.3 },
        { code: "SZL", name: "Swazi Lilangeni", rate: 18.44 },
        { code: "THB", name: "Thai Baht", rate: 36.83 },
        { code: "TJS", name: "Tajikistani Somoni", rate: 10.67 },
        { code: "TMT", name: "Turkmenistan Manat", rate: 3.5 },
        { code: "TND", name: "Tunisian Dinar", rate: 3.14 },
        { code: "TOP", name: "Tongan Pa'anga", rate: 2.34 },
        { code: "TRY", name: "Turkish Lira", rate: 32.9 },
        { code: "TTD", name: "Trinidad and Tobago Dollar", rate: 6.77 },
        { code: "TVD", name: "Tuvaluan Dollar", rate: 1.5 },
        { code: "TWD", name: "New Taiwan Dollar", rate: 32.54 },
        { code: "TZS", name: "Tanzanian Shilling", rate: 2616.81 },
        { code: "UAH", name: "Ukrainian Hryvnia", rate: 40.52 },
        { code: "UGX", name: "Ugandan Shilling", rate: 3698.76 },
        { code: "UYU", name: "Uruguayan Peso", rate: 39.31 },
        { code: "UZS", name: "Uzbekistani Som", rate: 12560.81 },
        { code: "VES", name: "Venezuelan Bolivar Soberano", rate: 36.41 },
        { code: "VND", name: "Vietnamese Dong", rate: 25469.15 },
        { code: "VUV", name: "Vanuatu Vatu", rate: 119.92 },
        { code: "WST", name: "Samoan Tala", rate: 2.73 },
        { code: "XAF", name: "Central African CFA Franc BEAC", rate: 612.88 },
        { code: "XCD", name: "East Caribbean Dollar", rate: 2.7 },
        { code: "XDR", name: "Special Drawing Rights", rate: 0.761 },
        { code: "XOF", name: "CFA Franc", rate: 612.88 },
        { code: "XPF", name: "CFP Franc", rate: 111.5 },
        { code: "YER", name: "Yemeni Rial", rate: 250.11 },
        { code: "ZAR", name: "South African Rand", rate: 18.44 },
        { code: "ZMW", name: "Zambian Kwacha", rate: 25.87 },
        { code: "ZWL", name: "Zimbabwean Dollar", rate: 13.6 },
    ];

    for (const currency of currencies) {
        await prisma.currency.create({
            data: {
                code: currency.code,
                name: currency.name,
                rate: currency.rate,
            },
        });
    }
}
